delivery/delivery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include,url
from restaurant import views
from rest_framework.routers import DefaultRouter
from api import views as api_views

router = DefaultRouter()
router.register(r'restaurants', api_views.RestaurantViewset)
router.register(r'menus', api_views.MenuViewset)

urlpatterns = [
    path('', views.IndexView.as_view()),
    url('^api/',include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('restaurant/', include('restaurant.urls')),
    path('api/menus/restaurant/<restaurant>', api_views.RestaurantMenuList().as_view()),
    path('api/menus/restaurant/<restaurant>/categories', views.get_restaurant_food_categories),    
]

if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/', views.RestaurantMenuView.as_view(), name='menu'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('empty-cart', views.empty_cart, name='empty-cart'),
    path('get-orders', views.get_orders, name='get-orders'),
    path('remove-item/', views.remove_item, name='remove-item'),
]

delivery/restaurant/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class State(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )
    name = models.CharField(max_length=250)
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES)

    def __str__(self):
        return self.name

class Lga(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )
    state = models.ForeignKey(State,related_name='lgas', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES)

    def __str__(self):
        return self.name

class Town(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )
    state = models.ForeignKey(State,related_name='towns', on_delete=models.CASCADE)
    lga = models.ForeignKey(Lga,related_name='lga_towns', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES)

    def __str__(self):
        return self.name

class FoodCategory(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Food Categories'

class Food(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    category = models.ForeignKey(FoodCategory, related_name='category', on_delete=models.CASCADE,
                default=None)
    # audit params
    create_time = models.DateTimeField(auto_now_add=True)
    create_user = models.ForeignKey(User,related_name='foods', on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    update_user = models.ForeignKey(User,related_name='user_foods', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class RestaurantCategory(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Restaurant Categories'

class Restaurant(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )
    state = models.ForeignKey(State, related_name='restaurants', on_delete=models.CASCADE)
    lga = models.ForeignKey(Lga,related_name='restaurants', on_delete=models.CASCADE)
    town = models.ForeignKey(Town,related_name='restaurant_town',null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, blank=True, null=True)
    address = models.TextField()    
    primary_phone = models.BigIntegerField()
    secondary_phone = models.BigIntegerField(blank=True,null=True)
    email = models.EmailField(max_length=250)
    website = models.URLField(blank=True)
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES)
    logo = models.ImageField()
    latitude = models.DecimalField(blank=True, null=True,max_digits=15,decimal_places=9)
    longitude = models.DecimalField(blank=True, null=True,max_digits=15,decimal_places=9)
    categories = models.ManyToManyField(RestaurantCategory)
    food_categories = models.ManyToManyField(FoodCategory)
    likes = models.PositiveIntegerField(default=0)
    # audit params
    create_time = models.DateTimeField(auto_now_add=True)
    create_user = models.ForeignKey(User,related_name='user_restaurants',on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    update_user = models.ForeignKey(User,related_name='restaurants', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Menu(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )
    restaurant = models.ForeignKey(Restaurant, related_name='restaurant_offering', on_delete=models.CASCADE)
    food = models.ForeignKey(Food,related_name='food_offerings', on_delete=models.CASCADE)    
    price = models.DecimalField(max_digits=8,decimal_places=2)
    image = models.ImageField()
    description = models.TextField(null=True)
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES)
    likes = models.PositiveIntegerField(default=0)
    # audit params
    create_time = models.DateTimeField(auto_now_add=True)
    create_user = models.ForeignKey(User,related_name='food_offering_creater', on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    update_user = models.ForeignKey(User,related_name='food_offering_updater', on_delete=models.CASCADE)

    def __str__(self):
        return self.food.name

    class Meta:
        unique_together = ('food', 'restaurant',)

    def food_name(self):
        return self.food.name

    def restaurant_address(self):
        return self.restaurant.address

    def restaurant_state(self):
        return self.restaurant.state.name    
    
    def restaurant_logo(self):
        return str(self.restaurant.logo)

    def menu_image(self):
        return str(self.image)

    def food_category(self):
        return self.food.category

class BooleanUtility:
    inside = False

delivery/restaurant/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import TemplateView, DetailView, ListView
from restaurant.models import Restaurant, FoodCategory, Menu, BooleanUtility
from rest_framework.authtoken.models import Token
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
import json

# Create your views here.
class IndexView(TemplateView):
    template_name = 'restaurant/index.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['restaurant_count'] = Restaurant.objects.count()
        context['food_categories'] = FoodCategory.objects.all()
        context['restaurants'] = Restaurant.objects.all()
        context['top_meals'] = Menu.objects.filter().order_by('-likes')[:3]
        return context


class RestaurantMenuView(TemplateView):
    template_name = 'restaurant/menu.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        restaurant = get_object_or_404(Restaurant, pk=self.kwargs['id'])
        context['restaurant'] = restaurant
        context['menus'] = Menu.objects.filter(restaurant=restaurant)
        context['token'] = Token.objects.get(user_id=1)
        return context


def get_restaurant_food_categories(request, **kwargs):
    """
    This view retrieves all the food categories belonging to a restaurant
    and all the foods belonging to each category
    """
    restaurant_id = kwargs['restaurant']
    restaurant = Restaurant.objects.get(pk=restaurant_id)
    food_categories = restaurant.food_categories.all()
    
    categories = []
    for category in food_categories:
        d = {}
        d['id'] = category.id
        d['name'] = category.name
        d['foods'] = []
        menus = Menu.objects.filter(restaurant=restaurant_id, food__category=category)
        for menu in menus:
            food = {}
            food['id'] = menu.food.id
            food['name'] = menu.food.name
            food['description'] = menu.description
            food['price'] = menu.price
            food['pic'] = menu.image.url
            food['likes'] = menu.likes
            d['foods'].append(food)
        categories.append(d)
        
    return JsonResponse(categories,safe=False)


@csrf_exempt
def add_to_cart(request):
    """
    This view adds a food item to a cart
    """    
    data = json.loads(request.body)    
    if 'cart' not in request.session:
        # if cart not yet initialized, initialize it then append new item
        request.session['cart'] = []
        request.session['cart'].append(data)
    else:
        BooleanUtility.inside = False
        item_cart = request.session['cart']
        for item in item_cart:
            # if item id exists in session, increase quantity
            if item['id'] == data['id']:
                BooleanUtility.inside = True
                item['qty'] = item['qty'] + 1
                
        request.session['cart'] = item_cart
        if BooleanUtility.inside == False:
            request.session['cart'].append(data)        
    
    request.session.modified = True
    return JsonResponse(data)
    

def empty_cart(request):
    if 'cart' in request.session:
        del request.session['cart']
        request.session.modified = True
    return JsonResponse({'status':'empty'})


def get_orders(request):
    if 'cart' in request.session:
        data = request.session['cart']
    return JsonResponse(data,safe=False)


@csrf_exempt
def remove_item(request):
    data = json.loads(request.body)
    
    if 'cart' in request.session:        
        item_cart = request.session['cart'] # assign cart session to variable
        for index, item in enumerate(item_cart):
            if item['id'] == data['id']:
                del item_cart[index] # delete selected item
        request.session['cart'] = item_cart # save item_cart back to session       
        request.session.modified = True        
        
    return JsonResponse(data)
    

delivery/restaurant/templates/restaurant/index.html
{% extends "index.html" %}
{% load staticfiles %}
{% block body %}
    
    <!-- banner part starts -->
    <section class="hero bg-image" data-image-src="{% static 'images/hero.jpg' %}">
        <div class="hero-inner">
            <div class="container text-center hero-text font-white">
                <h1>Order Delivery &amp; Take-Out </h1>
                <h5 class="font-white space-xs">Order your meals, snacks, drinks e.t.c from us</h5>
            </div>
        </div>
        <!--end:Hero inner -->
    </section>

    <div class="location-match text-xs-center">
        <div class="container">
            <span class="primary-color">{{restaurant_count}} Restaurants</span>
            <span> to Order From</span>            
        </div>
    </div>

    <section class="featured-restaurants">
        <div class="container">
            <div class="row">
                    <div class="col-md-4">
                    <div class="title-block float-left">
                        <h4 v-text="exam">Restaurants to Order From</h4>
                    </div>
                </div>
                <div class="col-md-8">
                    <!-- restaurants filter nav starts -->
                    <div class="restaurants-filter float-right">
                        <nav class="primary float-left">
                            <ul>
                                {% for cat in food_categories  %}
                                    <li>
                                        <a href="#" class="selected" data-filter="*">{{cat.name}}</a>
                                    </li>
                                {% endfor %}                                
                            </ul>
                        </nav>
                    </div>
                    <!-- restaurants filter nav ends -->
                </div>
            </div>

            <div class="row">
                {% for restaurant in restaurants  %}
                    <div class="col-12 col-md-6 col-lg-6 single-restaurant grill fish thaifood pizza">
                        <a href="{% url 'restaurant:menu' id=restaurant.pk %}">
                            <div class="restaurant-wrap">
                                <div class="row">
                                    <div class="col-12 col-sm-3 col-md-12 col-lg-3 text-xs-center">
                                        <img src="{{restaurant.logo.url}}" class="restaurant-logo" alt="Restaurant logo">
                                    </div>
                                    <div class="col-12 col-sm-9 col-md-9 col-lg-9">
                                        <h5>{{restaurant.name}}</h5>
                                        <span class="food-available">{{restaurant.categories.all | join:', '}}</span>
                                        <div class="bottom-part">
                                            <div class="mins">
                                                <i class="fa fa-motorcycle"></i>{{restaurant.address}}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="popular">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="title-block float-left">
                        <h2>Top Meals</h2>
                    </div>
                </div>
                <div class="col-md-8">
                    <!-- restaurants filter nav starts -->
                    <div class="restaurants-filter text-right">
                        <nav class="primary">
                            <ul>
                                {% for category in food_categories %}
                                    <li><a href="#">{{category.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                    <!-- restaurants filter nav ends -->
                </div>
            </div>
            <div class="row"  id="meal-app">                
                <top-meal v-if="menus.length" v-for="menu in menus" v-bind:key="menu.id" v-bind:menu="menu"></top-meal>
            </div>
        </div>
    </section>
    <script src="{% static 'js/app.bundle.js' %}"></script>
    
{% endblock body %}

delivery/restaurant/templates/restaurant/menu.html
{% extends "index.html" %}
{% load staticfiles %}
{% block body %}
    <div class="page-wrapper" id="menu-page">
        <span id='restaurant_id' style="display:none;">{{restaurant.id}}</span>
        <span id='token' style="display:none;">{{token}}</span>
        <span id='csrftoken' style="display:none;">{% csrf_token %}</span>
        <!-- top Links -->
        <div class="top-links">
            <div class="container">
                <ul class="row steps">
                    <li class="col-sm-4 col-md-4 col-lg-4 col-12 link-item active">
                        <span>1</span>
                        <a href="index.html">Choose Your Restaurant</a>
                    </li>
                    <li class="col-sm-4 col-md-4 col-lg-4 col-12 link-item">
                        <span>2</span>
                        <a href="restaurants.html">Select your favourite food(s)</a>
                    </li>
                    <li class="col-sm-4 col-md-4 col-lg-4 col-12 link-item">
                        <span>3</span>
                        <a href="checkout.html">Order and Pay online</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- end:Top links -->

        <!-- start: Inner page hero -->
        <section class="inner-page-hero bg-image" data-image-src="{% static 'images/hero.jpg' %}">
            <div class="profile">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12  col-md-4 col-lg-4 profile-img">
                            <div class="image-wrap">
                                <figure>
                                    <img src="{{restaurant.logo.url}}" alt="Profile Image">
                                </figure>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 profile-desc">
                            <div class="pull-left right-text white-txt">
                                <h6>
                                    <a href="#">{{restaurant.name}}</a>
                                </h6>
                                <a class="btn btn-small btn-green">Open</a>
                                <p>{{restaurant.categories.all | join:', '}}</p>
                                <ul class="nav nav-inline">
                                    <li class="nav-item">
                                        <a href="#">
                                            <i class="fa fa-motorcycle"></i> {{restaurant.address}} {{restaurant.town}}
                                        </a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- end:Inner page hero -->

        <div class="breadcrumb">
            <div class="container">
                <ul>
                    <li>
                        <a href="#" class="active">Home</a>
                    </li>
                    <li>
                        <a href="#">{{restaurant.name}}</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="container m-t-30">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                    <div class="sidebar clearfix m-b-20">
                        <div class="main-block">
                            <div class="sidebar-title white-txt">
                                <h6>Choose Meals</h6>
                                <i class="fa fa-cutlery pull-right"></i>
                            </div>
                            <ul>
                                <li>
                                    <a href="#headingTwo" class="scroll active">Rice</a>
                                </li>
                                <li>
                                    <a href="#headingTwo" class="scroll">Swallow</a>
                                </li>
                                <li>
                                    <a href="#headingTwo" class="scroll">Drinks</a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-6">
                    <div class="menu-widget m-b-30">
                        <div class="menu accordion" id="menuAccordion">
                            <category-item v-if="categories.length" v-bind:key="category.id" v-for="category in categories" v-bind:category="category">
                                <food-item v-on:get-orders="getOrders" v-for="food in category.foods" v-bind:key="food.id" v-bind:food="food"></food-item>
                            </category-item>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 col-lg-3">
                    <div class="sidebar-wrap">
                        <div class="widget widget-cart">
                            <div class="widget-heading">
                                <h3 class="widget-title text-dark">
                                    Your Cart Bowl
                                </h3>
                                <div class="clearfix"></div>
                            </div>
                            <!-- order rows -->
                            <order-item v-for="order in orders" v-bind:key="order.id" v-bind:order="order" v-on:remove-item="removeItem"></order-item>
                            <!-- order row ends -->
                            <div class="widget-body">
                                <div class="price-wrap text-xs-center">
                                    <p>TOTAL</p>
                                    <h3 class="value">
                                        <strong v-text="grandTotal">N3,500</strong>
                                    </h3>
                                    <p>+ N300 Shipping Added</p>
                                    <button onclick="location.href='checkout.html'" type="button" class="btn theme-btn w-100">Checkout</button>
                                    <button type="button" class="btn btn-danger mt-2 w-100" @click="clearCart">Clear Cart</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>        
        </div>


    </div><!-- page wrapper end-->
    <script src="{% static 'js/menu.bundle.js' %}"></script>
{% endblock body %}