delivery/delivery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include,url
from restaurant import views
from rest_framework.routers import DefaultRouter
from api import views as api_views

router = DefaultRouter()
router.register(r'restaurants', api_views.RestaurantViewset)
router.register(r'menus', api_views.MenuViewset)

urlpatterns = [
    path('', views.IndexView.as_view()),
    url('^api/',include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('restaurant/', include('restaurant.urls')),
    path('api/menus/restaurant/<restaurant>', api_views.RestaurantMenuList().as_view()),
    path('api/menus/restaurant/<restaurant>/categories', views.get_restaurant_food_categories),    
]

if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/', views.RestaurantMenuView.as_view(), name='menu'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('empty-cart', views.empty_cart, name='empty-cart'),
    path('get-orders', views.get_orders, name='get-orders'),
    path('remove-item/', views.remove_item, name='remove-item'),
]

delivery/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head
        content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="#">
    <title>Juzel Foods</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animsition.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>   
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>

<body class="home">
    <div class="site-wrapper animsition" data-animsition-in="fade-in" data-animsition-out="fade-out">
        <!--header starts-->
        <header id="header" class="header-scroll top-header headrom">
            <!-- .navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a href="{% url 'restaurant:index' %}"><img class="rounded" src="{% static 'images/logo.svg' %}" alt="Juzel Logo"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Cart</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- /.navbar -->
        </header>
        {% block body %}
        
        {% endblock body %}
        

        <footer class="footer">
        <div class="container">
            <!-- top footer statrs -->
            <div class="row top-footer">
                <div class="col-12 col-md-4 footer-logo-block color-gray">
                    <a href="index.html">
                        <img src="{% static 'images/logo.svg' %}" alt="Juzel Logo"> </a>
                    <span>Order Delivery &amp; Take-Out at Juzel Foods </span>
                </div>
                <div class="col-12 col-md-4 payment-options color-gray">
                    <h5>Payment Options</h5>
                    <ul>
                        <li>
                                <img src="{% static 'images/paystack.jpg' %}" alt="Paystack">
                        </li>
                        <li>
                                <img src="{% static 'images/mastercard.png' %}" alt="Mastercard">
                        </li>
                       
                    </ul>
                </div>
                <div class="col-12 col-md-4 address color-gray">
                    <h5>Address</h5>
                    <p>4-6 Independence Road, Gasahsh, Kano, Nigeria
                    </p>
                    <h5>Phone:
                        <a href="tel:+2347061076826">07061076826</a>
                    </h5>
                </div>
            </div>

        </div>
    </footer>
    
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/animsition.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-slider.min.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/headroom.js' %}"></script>
    <script src="{% static 'js/foodpicky.min.js' %}"></script>
</body>

</html>